import Navbar from "@/components/navbar";
import "@/stylesheets/globals.css";

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css'; // Importa el CSS
config.autoAddCss = false; // Evita que FontAwesome inserte su propio CSS


export const metadata = {
  title: "CyberSafe-Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
