import Footer from "@/layout/footer";
import Navbar from "@/layout/navbar";
import { Inter } from "next/font/google";
import "@/stylesheets/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cyber - Servicios tecnologicos y mucho mas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar />
            <main>
                {children}
            </main>
          <Footer />
      </body>
    </html>
  );
}